version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_rodevtest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rodevtest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rodev_network

volumes:
  postgres_data:
    driver: local

networks:
  rodev_network:
    driver: bridge
